# Generated by Django 4.1.2 on 2022-12-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employee_no', models.CharField(max_length=3)),
                ('mobile_no', models.CharField(max_length=10)),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD_APP.position')),
            ],
        ),
    ]
